server:
  port: 8080
    
jwt:
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwjve4E4ZjLA4D8bGrmlM
    YcdIGqDqsxkiC5Nyyi/019UfIbJBDLmAPEy0V4yNG0KAaKIhH1CLoB0m9AU3vgTW
    HkJOsv++zzpYpW519AkHn8npdbVGR79KQD5amctquUVv72GX2GImhsGCKB0lpw/r
    9KTMRb0WMxN88o4SHTJwxQl5f9ooENeEKe1OHAlQW25weS0y+DMCOaLS+8bPns2M
    gjLf0xSevdF602R92ZIRsBHY6bx9fWIVTbGwEBDfqjTDcpf/EyRHcXOE3p9AO48z
    v90OODaVnY3xg9y/x9X8uswZFZMdW28s6VO/ZXbDEWLUVIQaoew+KKJsfjLw1onV
    +QIDAQAB
    -----END PUBLIC KEY-----
  